title = " Pasear en tiempos de COVID19 "
baseURL = " / patico19 "
languageCode = " es "
theme = " gohugo-theme-ananke "
themesDir = " temas "

MetaDataFormat = " yaml "
DefaultContentLanguage = " en "
SectionPagesMenu = " main "
Paginate = 3  # esto se establece bajo para demostrar con contenido ficticio. Establecer en un número mayor
googleAnalytics = " "
enableRobotsTXT = true

[ mapa del sitio ]
  changefreq = " mensual "
  prioridad = 0.6
  filename = " sitemap.xml "

[ params ]
  favicon = " "
  description = " El último tema que necesitarás. Quizás " .
  facebook = " "
  twitter = " https://twitter.com/PCVillarcayo "
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
